package MovieList;
import books.book;
import Booklist.booklist;
import DB.DB;
import index.members;
import index.Main;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author magne
 */
public class MovieList extends javax.swing.JFrame {
    DB db = new DB();
    private static int age;
    private static String id = members.getUserId();

    public static String getId() {
        return id;
    }

    public static void setId(String id) {
        MovieList.id = id;
    }
    
    /**
     * Creates new form MovieList
     */
    public MovieList() {
        initComponents();
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width/2-getSize().width/2),
                (Toolkit.getDefaultToolkit().getScreenSize().height/2-getSize().height/2));
        try{
            db.DBopen();
        }
         catch (Exception e) {
                    System.out.println("SQLException : " + e.getMessage());
		}
        
        insertlist();
    }
    public void insertlist(){
        
        String SQL = "SELECT moviename, moviedir, movieprice, movieage from"
                + " movie group by moviename, moviedir, movieprice, movieage";
        try{
            db.pstmt = db.conn.prepareStatement(SQL);
            db.rs = db.pstmt.executeQuery();
            while(db.rs.next()){
                int r;
                r = movietable.getRowCount();
                for(int i=0; i<r; i++){
                    if(movietable.getValueAt(i,0)==null){
                        r = i;
                        break;
                    }
                }
                movietable.setValueAt(db.rs.getString(1),r,0);
                movietable.setValueAt(db.rs.getString(2),r,1);
                movietable.setValueAt(db.rs.getInt(3),r,2);
                movietable.setValueAt(db.rs.getInt(4),r,3);
            }
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        
    }
		
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        movietable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        blistmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        movietable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "영화이름", "감독", "가격", "연령제한"
            }
        ));
        movietable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movietableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(movietable);

        jLabel1.setText("영화 리스트");

        btnBook.setText("예매하기");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        jMenu1.setText("logout");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        blistmenu.setText("예매내역");
        blistmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blistmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(blistmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 129, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int userage(String id){
        String SQL = "select userage from member where userid = ?";
        try{
            db.pstmt = db.conn.prepareStatement(SQL);
            db.pstmt.setString(1, id);
            db.rs = db.pstmt.executeQuery();
            if (db.rs.next()){
                return db.rs.getInt(1);
            }
            return -1; //age없음
        }catch (Exception e) {
                    System.out.println("SQLException : " + e.getMessage());
        }return -2; //DB오류
    }
    
    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        age = userage(id);
        
        if (age < members.getMovieAge()){
            JOptionPane.showMessageDialog(null, "연령제한을 참고하세요.");
        }
        else{
            book book = new book();
            book.setVisible(true);
            setVisible(false);
        }
        
        
    }//GEN-LAST:event_btnBookActionPerformed

    private void movietableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movietableMouseClicked
        int i;
        i = movietable.getSelectedRow();
        members.setMovieName(movietable.getValueAt(i, 0).toString());
        members.setMovieDir(movietable.getValueAt(i, 1).toString());
        members.setMovieAge(Integer.parseInt(movietable.getValueAt(i, 3).toString()));
        
        
    }//GEN-LAST:event_movietableMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
                Main main = new Main();
        members.logout();
        setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void blistmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blistmenuMouseClicked
        booklist bl = new booklist();
        setVisible(false);
        bl.setVisible(true);
    }//GEN-LAST:event_blistmenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu blistmenu;
    private javax.swing.JButton btnBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable movietable;
    // End of variables declaration//GEN-END:variables
}
