/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Confirm;
import DB.DB;
import index.Main;
import index.members;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import Booklist.booklist;
import MovieList.MovieList;
import java.awt.Toolkit;

/**
 *
 * @author magne
 */
public class confirm extends javax.swing.JFrame {
    DB db = new DB();
    String seat = "";
    List a = (ArrayList)index.members.getSeatList();
    /**
     * Creates new form confirm
     */
    public confirm() {
        initComponents();
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width/2-getSize().width/2),
                (Toolkit.getDefaultToolkit().getScreenSize().height/2-getSize().height/2));
        try{db.DBopen();}
        catch (Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        movieinfo();
        
    }
    public void movieinfo(){
        moviename.setText(members.getMovieName());
        movieday.setText(members.getMovieDay());
        movietime.setText(members.getMovieTime());
        for(Object movieseat : a){
            seat += movieseat.toString() + " ";
        }
        movieseat.setText(seat);
        movieTotalP.setText(Integer.toString(members.getTotalP()) + "원");
        
        moviename.setEditable(false);
        movieday.setEditable(false);
        movietime.setEditable(false);
        movieseat.setEditable(false);
        movieTotalP.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        moviename = new javax.swing.JTextField();
        movieday = new javax.swing.JTextField();
        movietime = new javax.swing.JTextField();
        movieseat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        movieTotalP = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        blistmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("영화 명");

        jLabel2.setText("요    일");

        jLabel3.setText("시    간");

        jLabel4.setText("좌    석");

        jLabel6.setText("예매 확인");

        btnConfirm.setText("예 매 확 정");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("취소");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel7.setText("총 금액");

        jMenu1.setText("logout");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        blistmenu.setText("예매내역");
        blistmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blistmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(blistmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(movieday)
                                    .addComponent(movietime, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(movieseat, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(moviename, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(movieTotalP, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(moviename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(movieday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(movietime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(movieseat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(movieTotalP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnConfirm))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int choice = JOptionPane.showOptionDialog(null, "정말로 취소하시겠습니까?", "취소 확인 창", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,null,null);
        if(choice == JOptionPane.YES_OPTION){
            a.clear();
            members.setSeatList(a);

            MovieList mv = new MovieList();
            mv.setVisible(true);
            setVisible(false);
        }
        else{
            return;
        }

        
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        int i = insertbook();
        int k = updatemovie();
        
        for(Object j : a){
            insertjs(j);
        }
        
        if (i == -1 || k == -1)
            JOptionPane.showMessageDialog(null, "DB오류");
        else{
            a.clear();
            members.setSeatList(a);

            JOptionPane.showMessageDialog(null, "예매 완료!!");
            MovieList mv = new MovieList();
            mv.setVisible(true);
            setVisible(false);
        }
            
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Main main = new Main();
        members.logout();
        setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void blistmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blistmenuMouseClicked
        booklist bl = new booklist();
        setVisible(false);
        bl.setVisible(true);
    }//GEN-LAST:event_blistmenuMouseClicked
    public int insertbook(){
        String SQL = "insert into book values(?,?,?,?,?)";
        try{
            db.pstmt = db.conn.prepareStatement(SQL);
            db.pstmt.setString(1, members.getMovieNo());
            db.pstmt.setString(2, members.getUserId());
            db.pstmt.setInt(3, members.getCnt());
            db.pstmt.setString(4, members.getMovieDay());
            db.pstmt.setString(5, members.getMovieTime());
            return db.pstmt.executeUpdate();
        }catch (Exception e) {
                    System.out.println("SQLException : " + e.getMessage());
        }return -1;
    }
    public int insertjs(Object j){
        String SQL = "insert into bookjs values(?,?,?)";
        try{
            db.pstmt = db.conn.prepareStatement(SQL);
            
            db.pstmt.setString(1, members.getUserId());
            db.pstmt.setString(2, members.getMovieNo());
            db.pstmt.setString(3, j.toString());
            return db.pstmt.executeUpdate();
        }catch (Exception e) {
                    System.out.println("SQLException : " + e.getMessage());
        }return -1;
    }
    public int updatemovie(){
        String SQL = "update movie set moviecnt = moviecnt - ? where movieid = ?";
        try{
            db.pstmt = db.conn.prepareStatement(SQL);
            
            db.pstmt.setInt(1, members.getCnt());
            db.pstmt.setString(2, members.getMovieNo());
            return db.pstmt.executeUpdate();
        }catch (Exception e) {
                    System.out.println("SQLException : " + e.getMessage());
        }return -1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new confirm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu blistmenu;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField movieTotalP;
    private javax.swing.JTextField movieday;
    private javax.swing.JTextField moviename;
    private javax.swing.JTextField movieseat;
    private javax.swing.JTextField movietime;
    // End of variables declaration//GEN-END:variables
}
