package index;


import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import DB.DB;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class join extends javax.swing.JFrame {
    String id = null;
    String SQL = null;
    DB DBM  = new DB();
    Boolean IdCheck = false;
    Boolean nameCheck = false;
    Boolean numberCheck = false;
    Boolean ageCheck = false;

    /**
     * Creates new form MainFrame
     */
    public join() {
        initComponents();
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width/2-getSize().width/2),
                (Toolkit.getDefaultToolkit().getScreenSize().height/2-getSize().height/2));
        try{
            DB a = new DB();
            a.DBopen();
        }catch(Exception ex){
            System.out.println("SQLException : " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblJoin = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblPw = new javax.swing.JLabel();
        lblPwConfirm = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnComfirm = new javax.swing.JButton();
        btnJoin = new javax.swing.JButton();
        txtPw = new javax.swing.JPasswordField();
        txtPwComfirm = new javax.swing.JPasswordField();
        lblAge = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJoin.setText("회원가입");

        lblId.setText("아이디");

        lblPw.setText("비밀번호");

        lblPwConfirm.setText("비밀번호 확인");

        lblName.setText("성명");

        txtId.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnComfirm.setText("중복 확인");
        btnComfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComfirmActionPerformed(evt);
            }
        });

        btnJoin.setText("회원가입");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        lblAge.setText("나이");

        lblNumber.setText("전호번호");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnJoin)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblPwConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPwComfirm))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblPw, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPw))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComfirm))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtNumber)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJoin)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComfirm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPw)
                    .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwConfirm)
                    .addComponent(txtPwComfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnJoin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComfirmActionPerformed
        // TODO add your handling code here:
        if(txtId.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "아이디 칸이 비어 있습니다.");
            return;
        }
        id = txtId.getText();
        String idCheck = null;
        try{
            DBM.DBopen();
            SQL = String.format("select userId FROM member where userid = '%s'", id);
       
            DBM.pstmt = DBM.conn.prepareStatement(SQL);
            DBM.rs = DBM.pstmt.executeQuery();
            if(DBM.rs.next()){
                idCheck = (String)DBM.rs.getString(1);
                if(idCheck.trim().equals(id) || idCheck != null){
                    JOptionPane.showMessageDialog(null, id+"중복된 ID 입니다.");
                    return;
                }
        }else{
            JOptionPane.showMessageDialog(null, id+"사용이 가능합니다.");
            IdCheck = true;
        }
            DBM.DBclose();
        }catch(Exception ex){
            System.out.println("중복 SQL 오류 : " + ex);
        }
        

        
    }//GEN-LAST:event_btnComfirmActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        // TODO add your handling code here:
        if(!IdCheck){
            JOptionPane.showMessageDialog(null,"중복된 버튼을 눌러주세요.");
            return;
        }
        String pw = new String(txtPw.getPassword());
        String pwComfirm = new String(txtPwComfirm.getPassword());
        String age = txtAge.getText().trim();
        String number =txtNumber.getText().trim();
        id = txtId.getText().trim();
        String name = txtName.getText().trim();    
        if(id.length() == 0 || name.length() == 0  ||
            pw.length() == 0 || pwComfirm.length() == 0
                || age.length() == 0 || number.length() == 0){
            JOptionPane.showMessageDialog(null,"빈칸이 있습니다.");
            return;
        }
        if(pw.equals(pwComfirm) != true){
            JOptionPane.showMessageDialog(null, "비번이 일치하지 않습니다.");
            return;
        }
        if(name.matches(".*[ㄱ-ㅎㅏ-ㅣ가-힣]+.*")){
            nameCheck = true;
        }else{
            nameCheck = false;
        }
        
        nameCheck = Pattern.matches("^[가-힣]*$", name);
        numberCheck= Pattern.matches("^01(?:0|1|[6-9])-(?:\\d{3}|\\d{4})-\\d{4}$", number);
        ageCheck =Pattern.matches("^[0-9]*$", age);
        if(!nameCheck){
            JOptionPane.showMessageDialog(null, "이름은 한글로만 입력해 주세요.");
            return;
        }
        if(!numberCheck){
            JOptionPane.showMessageDialog(null, "휴대번호는 입력 방식이 틀렸습니다.(ex: 010-xxxx-xxxx)");
            return;
        }
        if(!ageCheck){
            JOptionPane.showMessageDialog(null, "나이 입력은 숫자로만 해주세요!");
            return;
        }
        //System.out.println(nameCheck);
        insertMembership(name, number, age, pw);
        JOptionPane.showMessageDialog(null, "회원가입이 완료 되었습니다.");
       reset();
       setVisible(false);
       Main main = new Main();
       main.setVisible(true);
    }//GEN-LAST:event_btnJoinActionPerformed

    
    
    private void reset(){
        txtId.setText("");
        txtPw.setText("");
        txtPwComfirm.setText("");
        txtName.setText("");
        IdCheck = false;
        
    }
    
    private void insertMembership(String name, String number, String age, String pw){
        try{
            DBM.DBopen();
            SQL = String.format("insert into member "
                    + "values ('%s', '%s', '%s', %d, '%s')", id, name, number, Integer.parseInt(age), pw);
            DBM.pstmt = DBM.conn.prepareStatement(SQL);
            DBM.pstmt.executeUpdate();
            DBM.DBclose();
        }catch(Exception ex){
            System.out.println("insert 문제 : " +ex);
        }
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(join.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(join.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(join.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(join.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new join().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComfirm;
    private javax.swing.JButton btnJoin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblJoin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblPwConfirm;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JPasswordField txtPwComfirm;
    // End of variables declaration//GEN-END:variables


}
