/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Booklist;

/**
 *
 * @author magne
 */
import DB.DB;
import index.members;
import java.util.ArrayList;
import MovieList.MovieList;
import index.Main;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
public class booklist extends javax.swing.JFrame {
    String movieid;
    int bookcnt;
    String movieday;
    String movietime;
    
    DB db = new DB();
    ArrayList<Integer> idlist;
    ArrayList<String> jslist;
    /**
     * Creates new form last
     */
    public booklist() {
        initComponents();
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width/2-getSize().width/2),
                (Toolkit.getDefaultToolkit().getScreenSize().height/2-getSize().height/2));
        try{db.DBopen();}
        catch (Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
        idlist = new ArrayList<>();
        jslist = new ArrayList<>();
        idlist = bookid();
        for(int id : idlist){
            jslist.add(js(id));
        }
        for (Object jsstr : jslist){
            int r;
            r = booktable.getRowCount();
            for(int i=0; i<r; i++){
                if(booktable.getValueAt(i,3)==null){
                    r = i;
                    break;
                }
            }
            booktable.setValueAt(jsstr,r,3);
        }
        for(int id : idlist){
            movieinfo(id);
        }
        
    }
    
    private ArrayList<Integer> bookid(){
        

        ArrayList<Integer> idlist = new ArrayList<>();
        try{
            String SQL = "SELECT distinct movieid from book where userid = ?";
            db.pstmt = db.conn.prepareStatement(SQL);
            db.pstmt.setString(1, members.getUserId());
            db.rs = db.pstmt.executeQuery();
            
            while(db.rs.next()){
                idlist.add(db.rs.getInt(1));
                
            }
            return idlist;
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }return idlist;
    }
    private String js(int id){
        String jsstr = "";
        try{
            String SQL = "SELECT moviejs from bookjs where movieid = ?";
            db.pstmt = db.conn.prepareStatement(SQL);
            db.pstmt.setInt(1, id);
            db.rs = db.pstmt.executeQuery();
            
            while(db.rs.next()){
                jsstr += db.rs.getString(1) + " ";
                
            }
            return jsstr;
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }return jsstr;
    }
    
    private void movieinfo(int id){
        String SQL = "SELECT distinct moviename, b.movieday, b.movietime from book b, movie mv"
                + " where mv.movieid = b.movieid and userid = ? and b.movieid = ?";
        try{
            db.pstmt = db.conn.prepareStatement(SQL);
            db.pstmt.setString(1, members.getUserId());
            db.pstmt.setInt(2, id);
            db.rs = db.pstmt.executeQuery();
            while(db.rs.next()){
                int r;
                r = booktable.getRowCount();
                for(int i=0; i<r; i++){
                    if(booktable.getValueAt(i,0)==null){
                        r = i;
                        break;
                    }
                }
                booktable.setValueAt(db.rs.getString(1),r,0);
                booktable.setValueAt(db.rs.getString(2),r,1);
                booktable.setValueAt(db.rs.getString(3),r,2);
            }
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        booktable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        bookdel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        booktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "영화이름", "요일", "시간", "좌석"
            }
        ));
        booktable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booktableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(booktable);

        jLabel1.setText("예매 내역 리스트");

        btnBook.setText("홈으로");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        bookdel.setText("예매 취소");
        bookdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookdelActionPerformed(evt);
            }
        });

        jMenu1.setText("logout");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1)
                        .addGap(0, 156, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(bookdel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookdel))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bookdel, btnBook});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booktableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booktableMouseClicked
        int row = booktable.getSelectedRow();
        
        movieday = booktable.getValueAt(row, 1).toString();
        movietime = booktable.getValueAt(row, 2).toString();
        
        
    }//GEN-LAST:event_booktableMouseClicked

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        MovieList mv = new MovieList();
        setVisible(false);
        mv.setVisible(true);

    }//GEN-LAST:event_btnBookActionPerformed

    private void bookdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookdelActionPerformed
        int choice = JOptionPane.showOptionDialog(null, "정말로 취소하시겠습니까?", "취소 확인 창", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,null,null);
        if(choice == JOptionPane.YES_OPTION){
            sel(movieday,movietime);
            delbook(movieday, movietime);
            deljs(movieid);
            up(movieday, movietime, bookcnt);
            booklist bl = new booklist();
            setVisible(false);
            bl.setVisible(true);
        }
        else{
            return;
        }
        
    }//GEN-LAST:event_bookdelActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Main main = new Main();
        members.logout();
        setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked
    
    private void sel(String day, String time){
        String SQL = "select movieid, bookcnt from book where movieday = ? and movietime = ?";
        try{
            db.pstmt = db.conn.prepareStatement(SQL);
            db.pstmt.setString(1, day);
            db.pstmt.setString(2, time);
            db.rs = db.pstmt.executeQuery();
            if(db.rs.next()){
                movieid = db.rs.getString(1);
                bookcnt = db.rs.getInt(2);
            }
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
    }
    private void delbook(String day, String time){
        String SQL = "delete from book where movieday = ? and movietime = ?";
        try{
            db.pstmt = db.conn.prepareStatement(SQL);
            db.pstmt.setString(1, day);
            db.pstmt.setString(2, time);
            db.pstmt.executeUpdate();
        }catch (Exception e) {
                    System.out.println("SQLException : " + e.getMessage());
        }
    }
    private void deljs(String id){
        String SQL = "delete from bookjs where userid = ? and movieid = ?";
        try{
            db.pstmt = db.conn.prepareStatement(SQL);
            db.pstmt.setString(1, members.getUserId());
            db.pstmt.setString(2, id);
            db.pstmt.executeUpdate();
        }catch (Exception e) {
                    System.out.println("SQLException : " + e.getMessage());
        }
    }
    private void up(String day, String time, int cnt){
        String SQL = "update movie set moviecnt = moviecnt+? where movieday = ? and movietime = ?";
        try{
            db.pstmt = db.conn.prepareStatement(SQL);
            db.pstmt.setInt(1, cnt);
            db.pstmt.setString(2, day);
            db.pstmt.setString(3, time);
            db.pstmt.executeUpdate();
        }catch (Exception e) {
                    System.out.println("SQLException : " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booklist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookdel;
    private javax.swing.JTable booktable;
    private javax.swing.JButton btnBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}